SELECT * FROM world.country WHERE NAME LIKE '%IND%';
SELECT COUNT(NAME), CONTINENT FROM WORLD.COUNTRY GROUP BY CONTINENT ;
SELECT COUNT(NAME), CONTINENT FROM WORLD.COUNTRY WHERE NAME LIKE '%IND%' GROUP BY CONTINENT ;
SELECT COUNT(NAME), CONTINENT FROM WORLD.COUNTRY GROUP BY CONTINENT HAVING COUNT(NAME) > 50 ;
SELECT NAME, CONTINENT FROM COUNTRY WHERE CONTINENT='North America';
