create database test;
show databases;
SELECT * FROM employee;
DESCRIBE EMPLOYEE;
USE TEST;
CREATE TABLE TEST.DEPARTMENT (DEPARTMENTID INT NOT NULL, DEPARTMENTNAME VARCHAR(30) NULL, PRIMARY KEY (DEPARTMENTID));
CREATE TABLE `employee` (
  `id` int NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `departmentid` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `departmentid_UNIQUE` (`departmentid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT COUNT(*) FROM EMPLOYEE WHERE DEPARTMENTID=1;
SELECT COUNT(*) FROM EMPLOYEE GROUP BY DEPARTMENTID;
SELECT LOWER(DEPARTMENTNAME) AS DEPTNAME FROM DEPARTMENT;
-- get the current date
SELECT SYSDATE();
select NOW();
SELECT SUBSTRING(NAME, 1,3) FROM EMPLOYEE;
CREATE TABLE NEWEMPLOYEE AS SELECT * FROM EMPLOYEE;
-- create an empty table with the same structure as some other table.
CREATE TABLE NEWEMPLOYEE SELECT * FROM EMPLOYEE WHERE 1=0;
DROP TABLE NEWEMPLOYEE;
SELECT * FROM EMPLOYEE WHERE NAME  NOT IN ('KRISHNA', 'DURGA');
SELECT * FROM EMPLOYEE WHERE NOT NAME='KRISHNA';
SELECT * FROM EMPLOYEE WHERE NAME <> 'KRISHNA';
ALTER TABLE EMPLOYEE ADD COLUMN SALARY INT NULL;
UPDATE EMPLOYEE SET SALARY=600000 WHERE ID IN (6);
SELECT SALARY+80 AS FULLNAME FROM EMPLOYEE WHERE ID=1;
-- remove duplicates from a table without using a temporary table. First insert duplicates
INSERT INTO EMPLOYEE (NAME, DEPARTMENTID , SALARY) VALUES ( 'KRISHNA', '1', 600000);
DELETE E1 FROM EMPLOYEE E1 INNER JOIN EMPLOYEE E2 WHERE E1.ID>E2.ID AND E1.NAME=E2.NAME AND E1.DEPARTMENTID=E2.DEPARTMENTID AND E1.SALARY=E2.SALARY;

SELECT * FROM EMPLOYEE WHERE MOD(ID, 3) = 0;
SELECT * FROM EMPLOYEE WHERE MOD(ID, 2) = 0;
SELECT * FROM EMPLOYEE WHERE MOD(ID, 2) <> 0;
-- OR
SELECT * FROM EMPLOYEE WHERE MOD(ID, 2) != 0;

SELECT * FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID=D.DEPARTMENTID;
SELECT * FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPARTMENTID=D.DEPARTMENTID;
SELECT * FROM EMPLOYEE E RIGHT JOIN DEPARTMENT D ON E.DEPARTMENTID=D.DEPARTMENTID;
SELECT * FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENTID=D.DEPARTMENTID;

SELECT * FROM EMPLOYEE E, DEPARTMENT D WHERE E.DEPARTMENTID=D.DEPARTMENTID;
ALTER TABLE EMPLOYEE RENAME COLUMN departmentid TO DEPARTMENTID;
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('1', 'KRISHNA', '1');
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('2', 'PRERITA', '1');
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('3', 'DURGA', '2');
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('4', 'MANOHAR', '3');
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('5', 'BABLI', '2');
INSERT INTO `test`.`employee` (`ID`, `NAME`, `DEPARTMENTID`) VALUES ('7', 'VISHAL', '2');
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENTID) VALUES ('6', 'KRISHNA', '1');
ALTER TABLE `test`.`employee` DROP INDEX `departmentid_UNIQUE`;

INSERT INTO DEPARTMENT (DEPARTMENTID, DEPARTMENTNAME) VALUES(4, 'TEACHER');
-- Get the 3rd highest ID
SELECT ID FROM EMPLOYEE ORDER BY ID DESC LIMIT 2,1;
SELECT MAX(ID) FROM EMPLOYEE;
SELECT SUM(ID) FROM EMPLOYEE;
SELECT DEPARTMENTID FROM EMPLOYEE GROUP BY DEPARTMENTID HAVING DEPARTMENTID>1 ;
SELECT DEPARTMENTID FROM EMPLOYEE WHERE DEPARTMENTID>1 GROUP BY DEPARTMENTID ;
CREATE INDEX EMP_ID ON EMPLOYEE(ID);

CREATE VIEW EMP_DEPT AS SELECT NAME, DEPARTMENTNAME FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID=D.DEPARTMENTID;
